{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c6516b02-25a6-4f75-9e77-dc88b56b1812",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# Set plot style\n",
    "sns.set(style=\"whitegrid\")\n",
    "\n",
    "# Streamlit interface\n",
    "st.title(\"Categorical Data Visualization\")\n",
    "\n",
    "# Upload CSV file\n",
    "uploaded_file = st.file_uploader(\"Upload your CSV file\", type=[\"csv\"])\n",
    "\n",
    "if uploaded_file is not None:\n",
    "    # Read the uploaded CSV\n",
    "    data = pd.read_csv(uploaded_file)\n",
    "    st.write(\"Data Preview:\")\n",
    "    st.write(data.head())\n",
    "\n",
    "    # Option to handle missing data\n",
    "    if st.checkbox(\"Drop missing data (optional)\"):\n",
    "        data = data.dropna(subset=['Country', 'Product', 'Import_Export', 'Category', 'Shipping_Method', 'Supplier', 'Payment_Terms'])\n",
    "\n",
    "    # 1. Bar Plot: Count of transactions by Country\n",
    "    st.subheader('Number of Transactions by Country')\n",
    "    fig1, ax1 = plt.subplots(figsize=(10, 6))\n",
    "    sns.countplot(y='Country', data=data, order=data['Country'].value_counts().index, palette='coolwarm', ax=ax1)\n",
    "    ax1.set_title('Number of Transactions by Country')\n",
    "    st.pyplot(fig1)\n",
    "\n",
    "    # 2. Count Plot: Count of transactions by Product\n",
    "    st.subheader('Number of Transactions by Product')\n",
    "    fig2, ax2 = plt.subplots(figsize=(10, 6))\n",
    "    sns.countplot(y='Product', data=data, order=data['Product'].value_counts().index, palette='Set2', ax=ax2)\n",
    "    ax2.set_title('Number of Transactions by Product')\n",
    "    st.pyplot(fig2)\n",
    "\n",
    "    # 3. Pie Chart: Distribution of Import/Export\n",
    "    st.subheader('Distribution of Import vs Export')\n",
    "    import_export_counts = data['Import_Export'].value_counts()\n",
    "    fig3, ax3 = plt.subplots(figsize=(8, 8))\n",
    "    ax3.pie(import_export_counts, labels=import_export_counts.index, autopct='%1.1f%%', startangle=90, colors=sns.color_palette('pastel'))\n",
    "    ax3.set_title('Distribution of Import vs Export')\n",
    "    st.pyplot(fig3)\n",
    "\n",
    "    # 4. Bar Plot: Count of transactions by Category\n",
    "    st.subheader('Number of Transactions by Category')\n",
    "    fig4, ax4 = plt.subplots(figsize=(10, 6))\n",
    "    sns.countplot(y='Category', data=data, order=data['Category'].value_counts().index, palette='muted', ax=ax4)\n",
    "    ax4.set_title('Number of Transactions by Category')\n",
    "    st.pyplot(fig4)\n",
    "\n",
    "    # 5. Pie Chart: Distribution of Shipping Method\n",
    "    st.subheader('Distribution of Shipping Methods')\n",
    "    shipping_method_counts = data['Shipping_Method'].value_counts()\n",
    "    fig5, ax5 = plt.subplots(figsize=(8, 8))\n",
    "    ax5.pie(shipping_method_counts, labels=shipping_method_counts.index, autopct='%1.1f%%', startangle=90, colors=sns.color_palette('Set3'))\n",
    "    ax5.set_title('Distribution of Shipping Methods')\n",
    "    st.pyplot(fig5)\n",
    "\n",
    "    # 6. Bar Plot: Number of Transactions by Supplier\n",
    "    st.subheader('Number of Transactions by Supplier')\n",
    "    fig6, ax6 = plt.subplots(figsize=(10, 6))\n",
    "    sns.countplot(y='Supplier', data=data, order=data['Supplier'].value_counts().index, palette='dark', ax=ax6)\n",
    "    ax6.set_title('Number of Transactions by Supplier')\n",
    "    st.pyplot(fig6)\n",
    "\n",
    "    # 7. Pie Chart: Distribution of Payment Terms\n",
    "    st.subheader('Distribution of Payment Terms')\n",
    "    payment_terms_counts = data['Payment_Terms'].value_counts()\n",
    "    fig7, ax7 = plt.subplots(figsize=(8, 8))\n",
    "    ax7.pie(payment_terms_counts, labels=payment_terms_counts.index, autopct='%1.1f%%', startangle=90, colors=sns.color_palette('Paired'))\n",
    "    ax7.set_title('Distribution of Payment Terms')\n",
    "    st.pyplot(fig7)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
